name: Build and deploy to GitHub Pages

on:
  push:
    branches:
      - main

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest
    permissions:
      contents: write       # allow pushes
      pages: write
      id-token: write

    steps:
      - name: Checkout repository (full history)
        uses: actions/checkout@v4
        with:
          fetch-depth: 0
          persist-credentials: true

      - name: Configure git user for deploy
        run: |
          git config --global user.name "github-actions[bot]"
          git config --global user.email "github-actions[bot]@users.noreply.github.com"

      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: 18

      - name: Install dependencies (including dev)
        run: npm ci --include=dev

      - name: Build client with Vite
        run: npx vite build

      - name: Bundle server with esbuild
        run: npx esbuild server/index.ts --platform=node --packages=external --bundle --format=esm --outdir=dist

      - name: Git diagnostics (help debug push errors)
        run: |
          echo "---- git remote ----"
          git remote -v || true
          echo "---- git ls-remote origin (may fail if no auth) ----"
          git ls-remote origin || true
          echo "---- git config ----"
          git config --list
          echo "---- whoami (git) ----"
          git --version

      - name: Deploy to GitHub Pages (gh-pages branch)
        uses: peaceiris/actions-gh-pages@v3
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_dir: ./dist/public
          allow_empty_commit: true
