name: Build and deploy to GitHub Pages

on:
  push:
    branches:
      - main

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest
    permissions:
      contents: read
      pages: write
      id-token: write

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: 18

      - name: Install dependencies (including dev)
        run: npm ci --include=dev

      - name: Build client with Vite
        run: npx vite build

      - name: Bundle server with esbuild
        run: npx esbuild server/index.ts --platform=node --packages=external --bundle --format=esm --outdir=dist

      - name: Upload artifact for GitHub Pages
        uses: actions/upload-pages-artifact@v1
        with:
          path: dist/public

      - name: Deploy to GitHub Pages
        uses: actions/deploy-pages@v1
